# Generated by Django 4.0 on 2022-11-29 05:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('BREAKFASTSTARTERS', 'BREAKFASTSTARTERS'), ('MAIN COURSE', 'MAIN COURSE'), ('DINNER', 'DINNER'), ('DESSERTS', 'DINNER')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=250)),
                ('opening_hours', models.CharField(max_length=150)),
                ('reservations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('restoran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.restourant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('menu', models.ManyToManyField(to='myapp.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('duty_type', models.CharField(choices=[('1', 'Chef'), ('2', 'Waiter'), ('3', 'Busboy'), ('4', 'Cleaning staff')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True)),
                ('restoran', models.ManyToManyField(to='myapp.Restourant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restoran',
            field=models.ManyToManyField(to='myapp.Restourant'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('restoran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.restourant')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=100)),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('description1', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('restorant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.restourant')),
            ],
        ),
    ]
