# Generated by Django 4.0 on 2022-11-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='restorant',
            new_name='Restorant_id',
        ),
    ]
