# Generated by Django 4.0 on 2022-11-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_restorant_about_restorant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Restorant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.restourant'),
        ),
    ]
