# Generated by Django 4.0 on 2022-12-06 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_menu_description_menu_name_menu_price_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descripton', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('descripton1', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True)),
                ('restoran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.restourant')),
            ],
        ),
    ]
