# Generated by Django 4.0 on 2022-12-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basitdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialstitle', models.JSONField()),
            ],
        ),
    ]
