# Generated by Django 4.0 on 2022-12-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_basitdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basitdata',
        ),
    ]
